output "cluster_name" { value = module.eks.cluster_name }
output "cluster_endpoint" { value = module.eks.cluster_endpoint }
output "cluster_certificate_authority_data" { value = module.eks.cluster_certificate_authority_data }
output "cluster_security_group_id" { value = module.eks.cluster_security_group_id }
output "container_insights_application_log_group_name" { value = module.eks.container_insights_application_log_group_name }
output "node_security_group_id" { value = module.eks.node_security_group_id }
output "oidc_provider_arn" { value = module.eks.oidc_provider_arn }
output "vpc_id" { value = module.networking.vpc_id }
output "vpc_cidr" { value = module.networking.vpc_cidr }
output "public_subnet_ids" { value = module.networking.public_subnet_ids }
output "private_subnet_ids" { value = module.networking.private_subnet_ids }
output "database_subnet_ids" { value = module.networking.database_subnet_ids }
output "database_subnet_group_name" { value = module.networking.database_subnet_group_name }
output "kms_key_arn" { value = module.security.kms_key_arn }
output "app_config_secret_arn" { value = module.security.app_config_secret_arn }
output "rds_instance_arn" { value = module.data_stores.rds_instance_arn }
output "rds_master_user_secret_arn" { value = module.data_stores.rds_master_user_secret_arn }
output "rds_endpoint" { value = module.data_stores.rds_endpoint }
output "redis_primary_endpoint" { value = module.data_stores.redis_primary_endpoint }
output "redis_replication_group_arn" { value = module.data_stores.redis_replication_group_arn }
output "app_storage_bucket_name" { value = module.app_storage.bucket_name }
output "app_storage_bucket_arn" { value = module.app_storage.bucket_arn }
output "dr_replica_bucket_name" { value = module.disaster_recovery.replica_bucket_name }
output "dr_region" { value = var.dr_region }
output "dr_backup_vault_arn" { value = module.disaster_recovery.backup_vault_arn }
output "cloudfront_domain_name" { value = try(module.edge[0].cloudfront_domain_name, null) }
output "cloudfront_certificate_arn" { value = module.certificates.certificate_arn }
output "alb_certificate_arn" { value = module.alb_certificates.certificate_arn }
output "cloudfront_hosted_zone_id" { value = try(module.edge[0].cloudfront_hosted_zone_id, null) }
output "route53_zone_id" { value = try(module.route53[0].zone_id, var.route53_zone_id) }
output "route53_fqdn" { value = try(module.route53[0].fqdn, null) }
output "cloudtrail_name" { value = module.governance.cloudtrail_name }
output "audit_bucket_name" { value = module.governance.audit_bucket_name }
output "backup_vault_arn" { value = try(module.backup[0].backup_vault_arn, null) }

